apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: sun20747/develop_zone:latest
          name: node-containers
          # resources:
          #   limits:
          #     memory: "10Mi"
          #     cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  # externalIPs:
  #   - "192.168.30.210"
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     kubernetes.io/ingress.class: node-app
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: node-app
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /nginx
#             backend:
#               serviceName: node-app
#               servicePort: 80
