apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: sun20747/develop_zone:latest
          name: node-containers
          # resources:
          #   limits:
          #     memory: "10Mi"
          #     cpu: "100m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: nginx
